# Menu
menu:
  Blog: /blog
  Links: /links.html
  Guestbook: /guestbook.html

force_serif: true
night_mode:
  auto: false
  force: false

# Third-party services
baidu_push: true
disqus_shortname:
baidu_analytics_id:
google_analytics_id:
