<header id="site-header" class="site-header wrap">
  <a class="site-logo" href="{{ url_for(theme.root || config.root) }}">
    {#- Change below into your own logo -#}
    <span class="b">H</span>
    <span class="w">4</span>
    <span class="w">0</span>
    <span class="w">4</span>
    <span class="b">B</span>
    <span class="b">I</span>
  </a>
  <a id="site-nav-switch" class="site-nav-switch">
    <span class="icon icon-menu b"></span>
  </a>
</header>